### ISSUE TITLE
No data is displaying if getting the data from a service call (Angular 6)?

### ISSUE THREAD

**Issue by yatharthmishra95** [czeckd/angular-dual-listbox#100]
Initially I am getting the data in both the source and destination lists if
I am saving the target list in the database for a pkid using an external submit button  ,After saving in the database, if I am searching the pkid and trying to display the related source and destination ,No data is getting populated, I am able to print both the source and destination data in the browser console.

 `this.apiService.getLogical(this.locationDetails.pkid).subscribe(data=>{
    this.source=data;
  
    console.log("source",this.source);
    
  });
  this.apiService.getMigrati(this.migrationDetails.migrationId).subscribe(data=>{
    this.target=data;
  
    console.log("target",this.target);
    
  });`

`<dual-list display="logicalDeviceName" [source]="source" [(destination)]="target"    height="150px"  ></dual-list>`

**Comment by czeckd** [comment]
Are all the items in the destination/target array also in the source array?

**Comment by mxm2go** [comment]
Firstly great library, thank you! And the ability to extend/customize is excellent.

I am having a similar issue. 
Following code works, when the source and target are declared locally;

template:
`<dual-list  [source]="source" [(destination)]="target"></dual-list>`
typescript:
```
  source = [
    { _id: 0, _name: 'Book1' },
    { _id: 1, _name: 'Book2' },
    { _id: 2, _name: 'Book3' },
    { _id: 3, _name: 'Book4' },
    { _id: 4, _name: 'Book5' },
    { _id: 5, _name: 'Book6' },
  ];
  target = [{ _id: 3, _name: 'Book4' },
  { _id: 4, _name: 'Book5' },
  { _id: 5, _name: 'Book6' },];
```

However, when I switch to using a service, there's nothing to display. 
From a different list on the same page, when an user is selected..
```
 displayBooksForSelectedUser(userID:number){

    this.source = this.bookService.getAllBooksForUser(userid);
    this.target = this.bookService.getFavoriteBooksForUser(userid);
  }
```

service signature
```
getAllBooksForUser(id: number): Book[] 
getFavoriteBooksForUser(id:number): Book[]
```
-------
```
getAllBooksForUser(id: number): Observable<Book[]> {
    const url = `${this.booksUrl}/${id}`;
    return this.http.get<ExtendedBook[]>(url)
        .pipe(map( (data,idx) =>  data.map(book => new Book(idx, book))),
          catchError (this.handleError)
        )
  }
```
```
/* convenience class used to display books in a list box */
export class Book {
  _id: number;
  _name: string;
  constructor(id: number, book: ExtendedBook){
    this._id = id;
    this._name = book.title+' : author :  '+book.author;
  }
}
```

Which when I look in the debugger or log to the console, looks like the following..
Book {_id: 0, _name: "Book1 : Author"}

I wonder if this is because the service returns a typed book array, which is not getting parsed properly.

**Comment by mxm2go** [comment]
My apologies. The error was in my code and not in the dual-listbox framework. My service was returning an array of Book objects with all of them having the _id: set to 0. 

I needed to include the index in the second map call to resolve this, 

getAllBooksForUser(id: number): Observable<Book[]> {
    const url = `${this.booksUrl}/${id}`;
    return this.http.get<ExtendedBook[]>(url)
        .pipe(map( (data,idx) =>  data.map((book, **idx**) => new Book(idx, book))),
          catchError (this.handleError)
        )
  }

**Comment by yatharthmishra95** [comment]
@czeckd Thanks for the answer ,the items of destination array were not present in the source array, as I set the souce array to null in the service call, but after setting the source array equal to the destination array in the service call the issue is resolved.
