### ISSUE TITLE
Can we add two lists in the source and destination?

### ISSUE THREAD

**Issue by yatharthmishra95** [czeckd/angular-dual-listbox#102]
Actually I want to add "Color id"," Color" columns  ,Ex- Color id:1 ,Color:Red ,Color id:2, Color:Green
![ANGULARDUALISTBOX](https://user-images.githubusercontent.com/19364421/55557554-b97ee700-5707-11e9-8c32-5fa05419cb40.jpg)  ,Thanks

**Comment by czeckd** [comment]
You can either develop a customized template (html) for this or, if you don't actually need columns pass in how you want a name to be made. From the source [dual-list.component.ts](https://github.com/czeckd/angular-dual-listbox/blob/master/lib/src/dual-list.component.ts):
```typescript
	// Allow for complex names by passing an array of strings.
	// Example: [display]="[ '_type.substring(0,1)', '_name' ]"
	protected makeName(item:any, separator = '_') : string {
```
So, something like this might work for your use case:
```html
[display]="['id', 'color']"
```
Assuming the parameters are `id` and `color` of course. This would make it show up as 1_Red, etc. Anything beyond that would need you to write a [custom dual listbox](https://github.com/czeckd/custom-dual-listbox) for your application.

**Comment by yatharthmishra95** [comment]
Thanks for the answer.
