### ISSUE TITLE
Unexpected token: name (BasicList)

### ISSUE THREAD

**Issue by Gajendrasinh** [czeckd/angular-dual-listbox#104]
Hello

Bellow error is given when i will try to build AOT build using ng build --prod command in angular 2

ERROR in vendor.3dc5fb37db37c2ace216.bundle.js from UglifyJs
Unexpected token: name (BasicList) [vendor.3dc5fb37db37c2ace216.bundle.js:41363,6]

**Comment by czeckd** [comment]
This project isn't using the Angular CLI. Use npm start to run and npm run dist to build the library distribution.

**Comment by czeckd** [comment]
This project has been converted now to use Angular CLI and Angular 8.
