### ISSUE TITLE
How do you extend DualListComponent?

### ISSUE THREAD

**Issue by shaikhspear16** [czeckd/angular-dual-listbox#108]
I am asked to make a super call and supply parameters to it of type 'IterableDiffers'. How can I achieve that ?

**Comment by czeckd** [comment]
The [custom-dual-listbox](https://github.com/czeckd/custom-dual-listbox) on github is an example project. In it you will see that you pass the differs to the super construction.

```ts
  constructor(differs: IterableDiffers) {
    super(differs);
  }
```
