### ISSUE TITLE
Changing key/display breaks moving

### ISSUE THREAD

**Issue by isaacrlevin** [czeckd/angular-dual-listbox#11]
If I set the key and display parameters, the destination list does not show up in the ui. It seems to be around the the filter that finds the item is using a "this" property which is not in scope. If I modify it to pass in the property, moving items between lists does not work

**Comment by czeckd** [comment]
Thanks. You uncovered a problem with the `findItemIndex` method when comparing items the source list to the internal lists. I believe I have the issue resolved now in the main branch if you could confirm the fix works for your use case.

**Comment by isaacrlevin** [comment]
Looks like it worked, issue closed!
