### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by yj854v** [czeckd/angular-dual-listbox#115]
Do you have responsive design available for this component, it would be great to have it. if so, please share the link on how to implement it.

**Comment by czeckd** [comment]
Put the component in a div and make the div size to whatever screen width you need it to be. The component sizes to 100% of the size of it's parent, so it will expand to fill the div.

Also will note the [demo](https://czeckd.github.io/angular-dual-listbox/) resizes correctly to screen size.

**Comment by yj854v** [comment]
Thanks for the quick and prompt response.
