### ISSUE TITLE
How to configure sorting option?

### ISSUE THREAD

**Issue by evandro-mota** [czeckd/angular-dual-listbox#128]
I'm currently displaying multiple properties on my list (name, value), and I need it to be sorted by value.
But the default option is sorting the list by name. How can I change that?

I've tried something like the code below on _destinationChange_
`this.available.list.sort((n1, n2) => n1._id - n2._id);`
But I can't get direct access to the properties of the object.

**Comment by czeckd** [comment]
Create a sort function like this in your source code, such as:
```ts
mySort = (a: any, b: any) => {
  return (a._id < b._id) ? -1 : ((a._id > b._id) ? 1 : 0); 
};
```
And add the `compare` attribute to your use of `dual-list` in the template, like so:
```html
<dual-list [compare]="mySort"></dual-list>

```

**Comment by evandro-mota** [comment]
Thanks!
