### ISSUE TITLE
Update destination from parent component

### ISSUE THREAD

**Issue by isaacrlevin** [czeckd/angular-dual-listbox#13]
I am trying to set the destination of the component from the parent and it is not updating properly. Basically I want to be able to "reset" the destination if the user does not save (for instance hitting close at the top). What I am seeing is the this.confirmed object is not being updated because it is populated only from the component itself. Is there an easy way to reset the destination ad-hoc?

**Comment by czeckd** [comment]
I'm guessing that you're assigning a new destination array on the parent rather than removing elements from the original destination array? Try making this change to allow that to work:

```
diff --git a/app/dual-list.component.ts b/app/dual-list.component.ts
index 3bef95f..87c12ba 100644
--- a/app/dual-list.component.ts
+++ b/app/dual-list.component.ts
@@ -100,8 +100,8 @@ export class DualListComponent implements DoCheck, OnChanges {
        @Input() destination:Array<any>;
        @Output() destinationChange = new EventEmitter();
 
-       private available:BasicList = new BasicList(DualListComponent.AVAILABLE_LIST_NAME);
-       private confirmed:BasicList = new BasicList(DualListComponent.CONFIRMED_LIST_NAME);
+       private available:BasicList;
+       private confirmed:BasicList;
 
        private sourceDiffer:any;
        private destinationDiffer:any;
@@ -122,11 +122,15 @@ export class DualListComponent implements DoCheck, OnChanges {
                }
 
                if (changeRecord['source']) {
+                       this.available = new BasicList(DualListComponent.AVAILABLE_LIST_NAME);
                        this.updatedSource();
+                       this.updatedDestination();
                }
 
                if (changeRecord['destination']) {
+                       this.confirmed = new BasicList(DualListComponent.CONFIRMED_LIST_NAME);
                        this.updatedDestination();
+                       this.updatedSource();
                }
        }
```

**Comment by isaacrlevin** [comment]
I was able to do it by iterating over this.destination in the updatedestination() method. Are there caveats to doing it this way?

**Comment by czeckd** [comment]
On the surface without seeing the code, my hunch is that it may be inefficient. But if it works for what you need, then that's half the battle. Did you happen to give the patch a try?

**Comment by DILEEPKUMAREBIX** [comment]
I have the same problem.
When i updating the destination array from parent component it is not properly updating, previous values are not clearing.
My Case:
I am updating destination from parent component on "comb box"(one element in parent component) selection change.

**Comment by DILEEPKUMAREBIX** [comment]
@isaac2004  "I was able to do it by iterating over this.destination in the updatedestination() method. "
May i know what you did exactly?

**Comment by czeckd** [comment]
I modified the [demo](https://czeckd.github.io/angular2-dual-listbox/demo/) to show how it works with programmatic changes to the arrays in the parent component. The `dual-list.component.ts` was also updated per my patch above. 

If the changes aren't working for your use case, please fork and modify with your use case or post some sample code demonstrating the problem. Thanks.
