### ISSUE TITLE
Angular 14

### ISSUE THREAD

**Issue by spike-rabbit** [czeckd/angular-dual-listbox#149]
Is it possible to bump angular to version 14 so that there is an ivy-compiled bundle? I can provide a PR

**Comment by czeckd** [comment]
It's possible, but with this using Bootstrap 3.x for styling, it's woefully out of date in other regards too.

**Comment by spike-rabbit** [comment]
ok, thanks for your reply. I'll discuss this with my team. Replacing the angular-dual-listbox would cause some effort, that's why we consider providing an angular update upstream here.
Guess we will then consider upgrading everything else as well.

**Comment by czeckd** [comment]
Your team could always pull the source code for the dual-listbox into your application and upgrade it as part of the app. I'll take a look at what is involved with going from ng10 to ng14. Maybe it makes sense even with Bootstrap 3?

**Comment by czeckd** [comment]
@spike-rabbit  angular-dual-listbox@7.0.0 is now Angular 14 and Ivy.

**Comment by spike-rabbit** [comment]
thanks a lot. The warning by the angular-cli is gone.
