### ISSUE TITLE
Source Code Release for v7.0.0

### ISSUE THREAD

**Issue by ssc4soft** [czeckd/angular-dual-listbox#160]
Hello and thank your for your great work! Unfortunately I have one issue with the latest version v7.0.0 in that (unlike the previous versions) it does not have a release with downloadable source code on https://github.com/czeckd/angular-dual-listbox/releases.

I'm using it in an app where the OSS clearing process requires such a release for allowing a new package version to production, so could you please publish v7.0.0. as a GitHub release? Thank you!

**Comment by czeckd** [comment]
@ssc4soft Done.
