### ISSUE TITLE
TypeError: Cannot read property 'diff' of undefined

### ISSUE THREAD

**Issue by jackjamieson** [czeckd/angular-dual-listbox#22]
Using Angular 4.0.2 I dropped the component in my project and am getting this TypeError when no options are supplied to the dual-list element.  It should handle the error more gracefully.

TypeError: Cannot read property 'diff' of undefined
    at DualListComponent.Array.concat.DualListComponent.buildAvailable (dual-list.component.ts:173)
    at DualListComponent.Array.concat.DualListComponent.ngDoCheck (dual-list.component.ts:164)

**Comment by czeckd** [comment]
Thanks for the report. I've [fixed the issue](https://github.com/czeckd/angular-dual-listbox/commit/9f7cdd571a0d856b7ba1d8681e2edd49e3381f3e) and the `dual-list` should now cause no errors if it is used with no options supplied.
