### ISSUE TITLE
Initialize list

### ISSUE THREAD

**Issue by bruceradtke** [czeckd/angular-dual-listbox#24]
Hello,

I am using your dual list and have gotten it working.  I have a simple question about datasets that are already defined. ( ie: the 'confirmed' array already has elements).  
What do I pass as the source and destination/confirmed?
Say my 'universe' of all available items are the numbers 1 - 10
[1,2,3,4,5,6,7,8,9,10]
But I want to pre-initialize the destination with the numbers 1-3
[1,2,3]
I assume I would take this into account when passing the arrays as follows:
source:   [4,5,6,7,8,9,10]
destination:  [1,2,3]

Is this correct? ( It doesn't appear to be working is why I am asking)

**Comment by czeckd** [comment]
The source should be: [1,2,3,4,5,6,7,8,9,10]
The destination should be: [1,2,3]

The source is the universe set of all possibilities. The destination is just the confirmed or chosen. 
The demo shows an example of this with 'Eureka' station.
