### ISSUE TITLE
runing "npm run start" is failling

### ISSUE THREAD

**Issue by r0lan2** [czeckd/angular-dual-listbox#34]
Hi,
I tried run the next command: "npm run start" and this is failling saying: "angular-dual-listbox@4.1.0 dist: `tools/mkdist`"... I can see that the issue is with the command "npm run dist"...... do you know what is the reason?

![output command](https://cloud.githubusercontent.com/assets/777801/25918978/9941ec76-35a3-11e7-9842-b47b84cd2467.png)

**Comment by czeckd** [comment]
Looks to be an incompatibility in the script between running on Linux/Unix and Cygwin.

To troubleshoot, I trying each command individually building up from each. So, first do:
```
rimraf tmp dist
```
If that works, then try:
```
rimraf tmp dist && \
echo 'Inlining...' &&  ts-node tools/inliner.ts
```
And so on.

Alternatively, it could just be a missing `#!/bin/bash` at the start of the script that is tripping up Cygwin.  I'll look into it when I get time to try on a Windows box.

**Comment by czeckd** [comment]
Actually, looks like you're running on just Windows, so I doubt a Linux shell script will work on it at all.

**Comment by czeckd** [comment]
@r0lan2 

Please try the approach in this [branch](https://github.com/czeckd/angular-dual-listbox/tree/unshell) to see if it works for you. Here's the [commit](https://github.com/czeckd/angular-dual-listbox/commit/a415ceb0975d1de2cd61165915fecb978b33f830).

It adds ``shelljs`` to the ``devDependencies`` of ``package.json`` and changes the ``mkdist`` to be:
```javascript  
var shell = require('shelljs');
var nm = 'node_modules/.bin/';

shell.exec(nm + '/rimraf tmp dist');
shell.echo('Inlining...');
shell.exec(nm + 'ts-node tools/inliner.ts');
shell.echo('Sourcing...');
shell.cp(['lib/angular-dual-listbox.module.ts', 'lib/basic-list.ts', 'lib/index.ts'], 'tmp/');
shell.echo('Transpiling...');
shell.exec(nm + 'tsc -p tsconfig-esm.json');
shell.echo('Rolling...');
shell.exec(nm + 'rollup -c rollup.config.js dist/index.js > dist/angular-dual-listbox.bundle.js');
shell.echo('Angularizing...'); 
shell.exec(nm + 'ngc -p tsconfig-esm.json');
shell.echo('Packaging...');
shell.exec(nm + 'ts-node tools/packager.ts');
shell.echo('Licensing...');
shell.cp(['README.md', 'LICENSE'], 'dist');
```

**Comment by czeckd** [comment]
Another option is to rename the script ``mkdist.sh`` and then run it with the ``sh.exe`` in Windows 10 as explained [here on stackoverflow](http://stackoverflow.com/a/34374894).

**Comment by czeckd** [comment]
Guessing one of these approaches worked for you.
