### ISSUE TITLE
Removing data from parent should not be allowed 

### ISSUE THREAD

**Issue by AngularTx** [czeckd/angular-dual-listbox#35]
Hi ,

I would like to use this component. I have tried the demo and its looks good. 
I have a scenario where I would like to keep the initial parent data towards the left asis , we should not remove anything from it or add anything to it. 
only the right hand side list we can get data from the parent list(add) and when deleting we should remove from right list . 

Can that be handled here with some changes?

**Comment by czeckd** [comment]
The source (parent) array never changes, only the display changes based on what is in the target array. Are you asking for the the source display to remain static so that if an entry is in the target array it also still appears in the source array?

**Comment by AngularTx** [comment]
yes, i want the data in the view to remain asis. dont want to remove or add
later to the parent .

**Comment by czeckd** [comment]
To keep the source display static would need a significant refactoring of the ``DualListComponent``. It is not a trivial change, since it is counter to one of the fundamental design assumptions I had when I created the component.
