### ISSUE TITLE
How can I check if have changes?

### ISSUE THREAD

**Issue by HigorSilvaRosa** [czeckd/angular-dual-listbox#37]
There are some output that i can use to detect when the value changed?

I loved this module!

**Comment by czeckd** [comment]
I'm guessing you mean detect change on the destination/target array? 

You could add something like ` (destinationChange)="myChange($event)"` where `<dual-list>` is used in the template:
```html
    <dual-list [sort]="keepSorted" [source]="source" 
        [(destination)]="confirmed" 
        (destinationChange)="myChange($event)"></dual-list>
```

And then in the code:
```typescript
    myChange(event) {
        console.log(event);
    }
```

**Comment by HigorSilvaRosa** [comment]
Thank you!
