### ISSUE TITLE
 TypeError: Cannot read property 'DEFAULT_FORMAT' of undefined

### ISSUE THREAD

**Issue by infact** [czeckd/angular-dual-listbox#40]
I am getting this error  when I try to load the page where dual ListBox is expected to show:

EXCEPTION: Uncaught (in promise): TypeError: Unable to get property 'DEFAULT_FORMAT' of undefined or null reference.

**Comment by czeckd** [comment]
Can you please provide a code example with enough details to reproduce it?

**Comment by czeckd** [comment]
Not reproducable.
