### ISSUE TITLE
Feature request for hook methods

### ISSUE THREAD

**Issue by webcat12345** [czeckd/angular-dual-listbox#41]
First of all thanks for your great component.

I am using this component for many project and it works as charm.

I would like to implement inline edit feature to this component. Could you please extend function for click event of list item?
Or is there any specific way to hook this?

**Comment by czeckd** [comment]
Would a `selectChange` event work in your use case? So a change to `dual-list.component.ts` like this to emit the event: 
```typescript
@Output() selectChange = new EventEmitter();
...
selectItem(list:Array<any>, item:any) {
    let pk = list.filter( (e:any) => {
        return Object.is(e, item);
    });
    if (pk.length > 0) {
        // Already in list, so deselect.
        for (let i = 0, len = pk.length; i < len; i += 1) {
            let idx = list.indexOf(pk[i]);
            if (idx !== -1) {
                list.splice(idx, 1);
                this.selectChange.emit( { key: item._id, selected: false });
            }
        }
    } else {
        list.push(item);
        this.selectChange.emit( { key: item._id, selected: true });
    }
}
```
This way anytime an item is selected or deselected an event would be sent back.

**Comment by dennisr90** [comment]
This would've been nice, but it's not there yet, right?

**Comment by czeckd** [comment]
No, and probably won't be put in the main project. But, it is straightforward to add by extending the component for your own project. There's a working example of this implemented in the [custom-dual-listbox](https://github.com/czeckd/custom-dual-listbox) sample project to show how it could be done.

**Comment by webcat12345** [comment]
https://github.com/webcat12345/angular-dual-listbox
I already forked and made an update to my own repository.
"angular-dual-listbox": "https://github.com/webcat12345/angular-dual-listbox/tarball/editable",

**Comment by Arezoo-Bozorgmehr** [comment]
Hey guys,

I would like to add the double click function in this Component. Could you please suggest me somethings.

Thanks
Arezoo

**Comment by czeckd** [comment]
@Arezoo-Bozorgmehr Sure, fork the [custom-dual-listbox](https://github.com/czeckd/custom-dual-listbox) sample project and change the template to add `(dblclick)="yourNewFunction()"` and then add `yourNewFunction()` to the your custom dual-list component.

**Comment by Arezoo-Bozorgmehr** [comment]
Hi David,
thank you so much, that works. I also  have tryed to apply Filter method ín
this project adding to template [filter]="filter" and then add
filter = true;
doFilter() {
this.filter = !this.filter;
}
in component but it dosn´t work. Could you please help me.

Thanks

2018-05-05 9:59 GMT+02:00 David Czeck <notifications@github.com>:

**Comment by Arezoo-Bozorgmehr** [comment]
Hi @David Czeck

I have solved the Filter problem adding a line code in template of
custom-dual-listbox.
Thanks again

2018-05-07 10:08 GMT+02:00 arezoo Bozorgmehr <arezoo.bozorgmehr16@gmail.com>
:
