### ISSUE TITLE
Duplicating items on selected items,

### ISSUE THREAD

**Issue by thilankascentic** [czeckd/angular-dual-listbox#46]
I am trying to load countries from a web service and assigning to dual-listbox . at the first time of calling service  both source and destination items are loading correctly,

but when calling service for second time, destination items are cloning,
if called service 3 times, destination items are cloning into 3 copies of each.

i tried clearing destination varible before assign values but its didnt worked, please help

![image](https://user-images.githubusercontent.com/29625709/30102863-87d557ca-930e-11e7-8b49-d1ea849f441f.png)

**Comment by czeckd** [comment]
Please provide a small application that reproduces the problem.

**Comment by czeckd** [comment]
I think I see where you're running into difficulty. I've created a branch with the potential fix: [rest-duplicate](https://github.com/czeckd/angular-dual-listbox/tree/rest-duplicate). The problem stems from having effectively different sources with the same destination and the way items were added to the list for display.

**Comment by thilankascentic** [comment]
Hi czeckd,
I have use this dual-list i in several locations of my application so if you fix above issue could you please tell me where should I change my existing code? or have you merged it into live?

**Comment by czeckd** [comment]
Try updating to version 4.3.2 and see if that resolves your duplicates problem.

**Comment by thilankascentic** [comment]
Thanks czecked,
yea Its solved in UI , I'll double check with the data binding as well and let you know if there any Issue.
Thanks again

**Comment by thilankascentic** [comment]
Hi ,
item duplicating issue is solved but I got another Issue, 
how can I clear the _destination_ items or _source_ ? I tried assigning destination to empty array and null but its didn't worked,

scenario,
![image](https://user-images.githubusercontent.com/29625709/30243627-a3cbff96-95cb-11e7-8312-b9f9009e7c77.png)

I have two button, on each clicked there will be a popup and that popup include our dual-listbox,

on the 1st button click, im getting data from a service and binding to source variable and destination variable, and it worked perfectly as bello
![image](https://user-images.githubusercontent.com/29625709/30243663-98b0e792-95cc-11e7-9d3b-ff472aa707c1.png)

then Im clicking my second button and It's onClick function is as bellow,
![image](https://user-images.githubusercontent.com/29625709/30243668-b8dfb96c-95cc-11e7-8c5d-651495243a59.png)

I tried to assigning above varibales to emoty array ([])  and to a null but the dual-list is still displaying previoesly loaded data as bellow.

![image](https://user-images.githubusercontent.com/29625709/30243678-e882be62-95cc-11e7-8938-94ea65ce14d1.png)

could you please tell me how can I clear binding variables ?

best regards
Thilanka,

**Comment by czeckd** [comment]
I tried to reproduce what you are seeing on my own, but was unable to do so. 

Assigning a new, empty array to the dual-list's destination should reset it. Also, setting the destination's array length to 0 would also reset it. 

If you can provide code with a reproducing example, I can take another look at it. 

Here's the code I used to test with:
```typescript
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { Http } from '@angular/http';
import { NgForm} from '@angular/forms';

import 'rxjs/add/operator/map';
import "rxjs/add/operator/debounceTime";

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html'
})

export class AppComponent implements AfterViewInit {
    @ViewChild('recordForm') rform:NgForm;

    queryString = '';
    source:Array<any> = [];
    confirmed:Array<any> = [];

    constructor(private http:Http) {
    }

    ngAfterViewInit() {
        setTimeout( () => {
            const qCtrl = this.rform.form.controls['query'];
            this.setup(qCtrl);
        }, 10);
    }
    private setup(qCtrl) {
        qCtrl.valueChanges.debounceTime(400).subscribe( value => {
            this.getListOfUsers(value);
        });
    }

    getListOfUsers(query:string) {
        if (query) {
            this.http.get('https://api.github.com/search/users?q='+query)
            .map(res => res.json())
            .subscribe((res) => {
                this.source = res.items;
            })
        }
    }

    clear() {
        // Either approach works.
        this.confirmed.length = 0;
        this.source.length = [];
    }
}
```
And the view:
```html
<div>
    <form #recordForm="ngForm">
        <input type="text" [(ngModel)]="queryString" name="query">
        <button (click)="clear()">Clear</button>
    </form>

    <dual-list [sort]="keepSorted" [source]="source" key="id" display="login"
        [(destination)]="confirmed" height="120px"></dual-list>

    <div style="display:flex;">
        <div>
            <pre style="height:100px;overflow:auto;margin: 8px 0;max-width:480px;">{{source|json}}</pre>
        </div>
        <div>
            <pre style="height:100px;overflow:auto;margin: 8px 0;max-width:480px;">{{confirmed|json}}</pre>
        </div>
    </div>
</div>
```
