### ISSUE TITLE
Can't get component to work in project created with angular cli

### ISSUE THREAD

**Issue by michaelblum** [czeckd/angular-dual-listbox#49]
I was unable to get angular-dual-listbox to work in my application.  I get the following webpack error:

WARNING in ./src/app/app.module.ts
52:12-29 "export 'DualListComponent' was not found in 'angular-dual-listbox'

following the installation instructions, I am getting the same error in a new project generated by angular cli.

**Comment by czeckd** [comment]
Please post your app.module.ts.

**Comment by michaelblum** [comment]
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AngularDualListBoxModule } from 'angular-dual-listbox';

import { AppComponent } from './app.component';
import { DemoAppComponent } from './demo-app/demo-app.component';

@NgModule({
  declarations: [
    AppComponent,
    DemoAppComponent
  ],
  imports: [
    BrowserModule,
    AngularDualListBoxModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**Comment by czeckd** [comment]
What happens if you change the first two lines? To:
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core'; 
```

**Comment by czeckd** [comment]
I have not been able to reproduce the error you are seeing.

I created a bare bones sample project using angular-cli 1.3.2 and angular-dual-listbox. You can clone it from here: [basic-dual-listbox-demo](https://github.com/czeckd/basic-dual-listbox-demo).

Please see if that works for you.

**Comment by czeckd** [comment]
Unreproducible and no further contact regarding issue.
