### ISSUE TITLE
export 'DualListComponent' was not found in 'angular-dual-listbox'

### ISSUE THREAD

**Issue by dennisr90** [czeckd/angular-dual-listbox#50]
Hi,

I'm getting the following warning:
> WARNING in ./src/app/admin/sources/sources.component.ts
> 38:87-104 "export 'DualListComponent' was not found in 'angular-dual-listbox'

This is when I do the following import in my component:
`import { DualListComponent } from 'angular-dual-listbox';`
`@ViewChild('dualcomp') dualcomp: DualListComponent;`

I am able to access `this.dualcomp`, so I don't see any errors/difficulties in doing what I want, but I still get this annoying warning. Do you have any idea why or how to resolve this?

**Comment by czeckd** [comment]
Try:
```typescript
import { DualListComponent } from 'angular-dual-listbox/dual-list.component';
```
See if that resolves it.

**Comment by dennisr90** [comment]
Seems like it did ! Thanks !!

Btw, great dual list ! Keep up the good work.
