### ISSUE TITLE
how to customize filter function

### ISSUE THREAD

**Issue by KiranWorks1061** [czeckd/angular-dual-listbox#54]
Hi,

Thank you so much for such a wonderful component. 
i have a scenario to customize the filter functionality like as below,
e.g: "Search This Text" : search as to be based on 3 keywords.

Is this possible to do with current existing functionality, please let me know.

Thanks

**Comment by czeckd** [comment]
To do this, you will need to make a customized component by extending the DualListComponent and overriding the ``onFilter(source:BasicList)`` method.

To make a custom filter like this, I'd think about taking the ``source.picker`` string and splitting it into substrings using a space delimiter and then looping over the ``source.list`` and filtering over the substrings. Either filtering the resulting list with each substring or doing an OR based filter if you want all possible matches.  

For an example of how to extend and customize angular-dual-listbox, please take a look at the [custom-dual-listbox](https://github.com/czeckd/custom-dual-listbox) project and how the [CustomListboxComponent](https://github.com/czeckd/custom-dual-listbox/blob/master/src/app/custom-listbox/custom-listbox.component.ts) overrides the method ``selectItem(list:Array<any>, item:any)`` for example on how to get started.

Good luck!
