### ISSUE TITLE
404 not found issue

### ISSUE THREAD

**Issue by BiswanathGitHub** [czeckd/angular-dual-listbox#58]
Hi,

I followed every steps mentioned, but after npm start,

I am getting this:
zone.js:2933 GET http://localhost:3000/angular-dual-listbox 404 (Not Found)

Please help

**Comment by czeckd** [comment]
I need more details and / or code examples of what you've tried. If you're really stuck, please clone the [basic-dual-listbox-demo](https://github.com/czeckd/basic-dual-listbox-demo) project for a working example on how to use the component.
