### ISSUE TITLE
Please, help me with drag and drop!

### ISSUE THREAD

**Issue by pedrofarbo** [czeckd/angular-dual-listbox#59]
Hey my friend, first i want to thank you about this amazing component, so i'm using this component in my project and i need to know if you can help me with disable the drag and drop feature or how to get the reference of end of the object drop for condicioning one button. I want to show the button only when the user drop the object out. I already make this two functions to make this happen in the add button and the remove button, look this functions below: 

    $('[name = "addBtn"]').on('click', function () {
      _component.change();
    });`

    $('[name = "removeBtn"]').on('click', function () {
      _component.change();
    });`

Where these methods call the method change() and the method change(), change a boolean to true to show the button to save the confirmed list in the MySQL.

Any ideas to change the boolean to true when the user drop the object? 

Thank you so much for your time! 

Best Regards,
Pedro Farbo - VetorWeb

**Comment by czeckd** [comment]
I updated the angular-dual-listbox npm package to v4.5.0, which will allow you to disable drag-and-drop. Here is an example on how to disable drag-and-drop with angular-dual-listbox@4.5.0.

```html
<dual-list [source]="source" [(destination)]="confirmed" [format]="{draggable:false}">
</dual-list>
```
If you need to capture when the destination has changed so you can save to the MySQL database, then use the `destinationChange` event, like so in your html template:

```html
<dual-list [source]="source" [(destination)]="confirmed" 
    (destinationChange)="saveToDatabase($event)" [format]="{draggable:false}">
</dual-list>
```
And in your TypeScript code:
```ts
saveToDatabase(e) {
    // Stub code, log event to console for now.
    console.log(e);
    // TODO: initiate database interaction.
}
```

**Comment by pedrofarbo** [comment]
Thanks my friend! Issue resolved!
