### ISSUE TITLE
install with angular 5

### ISSUE THREAD

**Issue by kopagana** [czeckd/angular-dual-listbox#62]
we are trying to install this plugin while using angular 5 with `$ npm i angular-dual-listbox --save` command.
the files `tools` and `rollup.config.js` are not downloaded with the rest of the files.
does manually download them and inject them to the project is acceptable move?

we used the angular-dual-listbox in angular 4 version and it worked fine but everything changed when the version 5 "attacked" XD

thanks a head.

**Comment by czeckd** [comment]
If you want the development scripts and configuration files, you will need to clone the repository.
```shell
git clone https://github.com/czeckd/angular-dual-listbox.git
```
