### ISSUE TITLE
Listen to changes

### ISSUE THREAD

**Issue by fandridis** [czeckd/angular-dual-listbox#63]
Hi there,

I have been using this dual-listbox for a while and it works and looks great, good job!
Is it possible to somehow get notified when an item is added or removed from the target/destination box?

For example in case I want to run a function every time the user adds/remove an item.

Thanks in advance!

**Comment by czeckd** [comment]
Yes, you can hook into the change event like so: `(destinationChange)="echo($event)"`

From demo-app.component.ts
```html
<dual-list [sort]="keepSorted" [source]="source" [key]="key" [display]="display" 
        [filter]="filter" [(destination)]="confirmed"
        (destinationChange)="echo($event)" 
        height="265px" [format]="format" [disabled]="disabled"></dual-list>
```
```ts
    echo(e) {
        console.log(e);
    }
```

The event gives an array of all members in the target/destination.

**Comment by nlptr** [comment]
HI when i try to console the above event, it only gives me the items that are added to destination array. It doesn't say anything about the event type (to know if its add/remove). How do i know the type of event?
