### ISSUE TITLE
How to display data in Dual Listbox

### ISSUE THREAD

**Issue by AulonaBinaj** [czeckd/angular-dual-listbox#64]
component.ts
```
 permissions: Array<Permissions> = [];

 ngOnInit() {
   this.ps.getAllPermission().subscribe(
      permissions => {
        console.log(permissions)
        this.permissions = permissions.map((permission) => {
          return new Permissions(permission);
        });
      }
    );}
```
component.html
 

```
 <div class="container-fluid">
  <dual-list [sort]="permissions" [key]="permissions" [(display)]="display"  [source]="permissions" [(destination)]="target"></dual-list>
  </div>
```

**Comment by czeckd** [comment]
Per your typescript code, you have an array of permissions. But you're not providing the dual-list component enough information on how to interact with it.

```html
<dual-list [sort]="permissions" [key]="permissions" [(display)]="display" 
   [source]="permissions" [(destination)]="target"></dual-list>
```

1. sort is a boolean, so should be either true or false.
1. key is the unique key identifier in your Permission object. Something that is unique to each Permission object in the array such as an id or primary key.
1. display is a text attribute in your Permissions object that is what the user would see in the dual-list.
1. target is an array, usually empty to begin with, in your typescript. I didn't see it in your code example, but you may have it already part of your code.

So, for example, say this is your Permission object:
```typescript
export class Permission {
   id: number;
   name: string;
}
```

Then, your dual-list would be configured in the html template like so:
```html
<dual-list [sort]="true" [key]="id" [(display)]="name" 
   [source]="permissions" [(destination)]="target"></dual-list>
```

**Comment by prithvirajrmd2015** [comment]
Hi consider my array object is structured like 
`{type:textfield, 
        controldef:{
           key:"1",label:"fullname"}}`
now i want to use the key as my identifies so n html template i gave 

`<dual-list [sort]="true" [key]="controldef.key" [(display)]="name" 
   [source]="permissions" [(destination)]="target"></dual-list>` 


but its not working can you suggest me what i have to do.
