### ISSUE TITLE
Updating to disable drag/drop and  display multi line records

### ISSUE THREAD

**Issue by sukumarkonduru** [czeckd/angular-dual-listbox#71]
David, 
Thanks for providing excellent component. 

I need to modify the code to incorporate following.
1. Remove drag/drop (Is it possible with any property?)
2. Display each item as 3 line record
3. Move add remove to middle and remove buttons on the bottom.

Let me know any tips for completing those. I created project with just copying files under  lib/src as a module and imported it  and it is working as well.  Now I can modify the source code for any changes needed. Appreciate your time on any high-level tips.

**Comment by czeckd** [comment]
1. Per the [README.md](https://github.com/czeckd/angular-dual-listbox/blob/master/README.md), you can remove drag-and-drop via a format object passed in the html. For example:
```html
<dual-list [source]="source" [(destination)]="confirmed"
    [format]="{ draggable: false }"></dual-list>
```
2. You can style the dual-list anyway you need by extending the component and providing it with a new template. I have a sample project with an example here: [czeckd/custom-dual-listbox](https://github.com/czeckd/custom-dual-listbox). This is how it looks without really needing to incorporate the angular-dual-listbox source code in your project :
![Custom Dual ListBox](https://raw.githubusercontent.com/czeckd/custom-dual-listbox/master/images/custom.png)

3. See 2.

**Comment by sukumarkonduru** [comment]
Thanks David,  It is easy to extend the code. I only have few months of angular experience and struggling to understand following snippets. However, it is an interesting application to use as a project to understand better on angular/typescript/javascript.

@Input() id = `dual-list-${nextId++}`; //guess used fro drag/drop

ngOnChanges(changeRecord: {[key:string]:SimpleChange}) //guess name value pairs  name:value

constructor(private differs:IterableDiffers) {
this.sourceDiffer = this.differs.find(this.source).create(null); // don't know
const sourceChanges = this.sourceDiffer.diff(source);

I will extend now and go through code later. Appreciate taking time to reply.

**Comment by czeckd** [comment]
The DualListComponent has ``var nextId = 0;`` which is the default if the id isn't provided as an Input() and yes it is there for drag-and-drop.

Read the Angular docs on [OnChanges ](https://angular.io/api/core/OnChanges)and [SimpleChange](https://angular.io/api/core/SimpleChange).

The Angular docs on [IterableDiffers](https://angular.io/api/core/IterableDiffers) is a bit sparse, but basically that bit of code is using a factory to create a differ, the null being passed in is what to track by, in this case nothing. If you want more details, read Minko Gechev's article on [Understanding Differs](http://blog.mgechev.com/2017/11/14/angular-iterablediffer-keyvaluediffer-custom-differ-track-by-fn-performance/). The pattern I used in the component is old, but you can still see an example of its use in this old Angular 2 [plnkr](http://embed.plnkr.co/qZf6yv/) in app.component.ts :

```typescript
export class AppComponent {
  heroes = HEROES;
  differ:IterableDiffer;
  
  constructor(differs:IterableDiffers) {
    this.differ = differs.find([]).create(null);
  }
  
  removeHero(index: number) {
    this.heroes.splice(index, 1);
  }
  
  trackHeroes(index: number, hero: Hero) {
    return hero.id;
  }
  
  ngDoCheck() {
    const changes = this.differ.diff(this.heroes);
    if (changes) {
       console.log('new change');// for splitting up changes
       changes.forEachAddedItem(r => console.log('added ', r));
       changes.forEachRemovedItem(r => console.log('removed ', r))
       changes.forEachMovedItem(r => console.log('moved ', r))
     }
   }
}
```
The plnkr no longer runs.

**Comment by sukumarkonduru** [comment]
Thanks David for taking time to reply in detail.  I was going through dual list from last 2 days. I did not use Javascript for a while  and this project is helping me to refresh and also learn new Javascript APIs and learn how Angular is used with all the lifecycle methods and template. I like the demo usage sample also as being powerful to customize the application.

One question I have is to create IterableDiffer  object, find is passed empty array or Iterable object. I guess both return same object and is invoked create method. In dual list project iterable is passed but most samples shows []. I need to read little more on it.

I am trying to understand how list,sift, and pick are used. It seems pick is used whenever user selects an element.  sift is used in ngFor to display.   Not sure source of truth is list or sift and how they being used. I will  go through the code again during my free cycles.

I am also trying to understand how label changing methods  like filterBtn() is being called when user clicks filter and doFilter() happens.
<button class="btn btn-default" (click)="doFilter()">{{filterBtn()}}</button>
						<button class="btn btn-default" (click)="doDisable()">{{disableBtn()}}</button>

**Comment by edoura** [comment]
> 1. Per the [README.md](https://github.com/czeckd/angular-dual-listbox/blob/master/README.md), you can remove drag-and-drop via a format object passed in the html. For example:
> 
> ```
> <dual-list [source]="source" [(destination)]="confirmed"
>     [format]="{ draggable: false }"></dual-list>
> ```

I'm using [custom](https://github.com/czeckd/custom-dual-listbox) and ```[format]="{ draggable: false }"``` it's not working

**Comment by czeckd** [comment]
@edoura without seeing your template in your custom, it is impossible to troubleshoot. If I had to guess, then it would be you omitted code like `[draggable]="!disabled && format.draggable"` from the `<li #itmConf>` in the `<div class="record-picker">`.

**Comment by edoura** [comment]
Thank you very much @czeckd. My model is very similar to the one you provided. It was exactly what you observed :+1:
