### ISSUE TITLE
Filter can not detect upper or lower case

### ISSUE THREAD

**Issue by emrahsenturk** [czeckd/angular-dual-listbox#75]
Hi,

I am using Turkish alphabet. My dual-list have some texts like MİHRİCAN. I am writing "mi" to filter input. But it doesn't find anything.

Any solution for this problem?

**Comment by czeckd** [comment]
Is your browser locale set to 'tr_TR' or something else? This is a problem with the dual-list using `toLowerCase()` for the filtering instead of `toLocaleLowerCase()`. 

If it is Turkey, then I change do a new release to use `toLocaleLowerCase()` and I believe it'll take care of it. If you're using a different locale, then the escape codes will need to be removed as well.

You could create a [custom-dual-listbox](https://github.com/czeckd/custom-dual-listbox) and override the `onFilter` function to do something like this:

```javascript
    private standardizeString(text:string) : string {
        return text.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    }

    onFilter(source:BasicList) {
        if (source.picker.length > 0) {
            const filtered = source.list.filter( (item:any) => {
                if (Object.prototype.toString.call(item) === '[object Object]') {
                    if (item._name !== undefined) {
                        return this.standardizeString(item._name).indexOf(this.standardizeString(source.picker)) !== -1;
                    } else {
                        return this.standardizeString(JSON.stringify(item)).indexOf(this.standardizeString(source.picker)) !== -1;
                    }
                } else {
                    return this.standardizeString(item).indexOf(this.standardizeString(source.picker)) !== -1;
                }
            });
            source.sift = filtered;
            this.unpick(source);
        } else {
            source.sift = source.list;
        }
    }
```
But let me know if just switching to `toLocaleLowerCase()` solves your problem and if it does I'll get a new build out.

You can test it in the console:
```javascript
console.log('MİHRİCAN'.toLocaleLowerCase().indexOf('mih'.toLocaleLowerCase()) !== -1);
```
My locale is 'en' so, it comes out 'false', but if I explicitly set it to 'tr', then the result is true:
```javascript
console.log('MİHRİCAN'.toLocaleLowerCase('tr').indexOf('mih'.toLocaleLowerCase('tr')) !== -1);
```

**Comment by emrahsenturk** [comment]
`console.log('MİHRİCAN'.toLocaleLowerCase().indexOf('mih'.toLocaleLowerCase()) !== -1);`

When I try thisi it comes out false.

`console.log('MİHRİCAN'.toLocaleLowerCase('tr').indexOf('mih'.toLocaleLowerCase('tr')) !== -1);`

But when I try this, it is returning true.

I guess toLocaleLowerCase('tr') solves my problem.

Now what will I do? Where will I use this code :)

**Comment by czeckd** [comment]
@emany : I'll get a new package with `toLocaleLowerCase` in place in the next 24 hrs.

**Comment by emrahsenturk** [comment]
@czeckd ok, thanks. So how can i update dual-listbox package?

**Comment by czeckd** [comment]
Release 4.6.3 is now on npmjs.com, so just:
```sh
npm i --save angular-dual-listbox@latest
```

**Comment by emrahsenturk** [comment]
@czeckd I installed lastest version. But my problem is not resolved.

It is still not finding "mi" in "MİHRİCAN".

**Comment by czeckd** [comment]
Well that's disappointing. That leaves you the option of making a custom dual-list component with an override of `onFilter` as I [described earlier above](https://github.com/czeckd/angular-dual-listbox/issues/75#issuecomment-374456822) that strips out the escape codes, or not using filtering, or not using the dual-list component.

**Comment by czeckd** [comment]
I've run up to a [TypeScript bug](https://github.com/Microsoft/TypeScript/issues/11056#issuecomment-354258195)  trying to explicitly set the locale as `toLocaleLowerCase('tr')`. The function definition for toLocaleLowerCase is incomplete and thus won't transpile with arguments without modifying the lib.es5.d.ts definition for it. If I can work around it, then I could provide a way to programatically set the locale without needing to override the `onFilter` function in the dual-list component.

**Comment by emrahsenturk** [comment]
@czeckd Ok, Do I wait for you or use a custom-dual-list?

**Comment by czeckd** [comment]
Depends how soon you need it working. If you need it today or soon, then go custom. If you can wait a few days, then I might have something.

**Comment by emrahsenturk** [comment]
@czeckd I can wait a few days. So I am waiting you. Thank you for your interest.

**Comment by czeckd** [comment]
@emany Please try this again. I've update the angular-dual-list@4.7.0 with support for explicitly setting the locale.
```sh
npm i --save angular-dual-listbox@latest
```
Add to your dual-list a format object with the locale set to be 'tr_TR' or 'tr'. 
Example:

```html
<dual-list [source]="source" [(destination)]="confirmed" [format]="{ locale: 'tr' }" >
</dual-list>
```
With any luck, the filter on dual-list will support lowercase İ correctly.

**Comment by emrahsenturk** [comment]
@czeckd My problem solved. Thank you for everything.
