### ISSUE TITLE
Problem loading items to "confirmed" or the selected area of the dual-listbox.

### ISSUE THREAD

**Issue by damith-pyl** [czeckd/angular-dual-listbox#79]
Hi, I'm having a hard time integrating this to my angular 4 app which use google firestore as the back-end. 
Can you provide a sample on how to load items to both "source" and "confirmed" arrays. Even though I could load items to "confirmed" array, I cannot see them in the UI.

**Comment by czeckd** [comment]
The source array contains all the available items. So for an item to be in the confirmed array, it must also exist in the source array.

```typescript
    origin = [ 'alpha', 'beta', 'gamma', 'delta' ];
    target = [ 'gamma' ];
```
The confirmed array will have 'gamma' in it and 'gamma' will not be displayed in the source array, unless it is removed from the confirmed array.

To see this in action, look at how only the confirmed array changes in the [demo](https://czeckd.github.io/angular-dual-listbox/demo/). Source code for the demo is in the project [here](https://github.com/czeckd/angular-dual-listbox/blob/master/app/demo-app.component.ts).

**Comment by damith-pyl** [comment]
Thanks, solved the issue.
