### ISSUE TITLE
Update to Angular 6

### ISSUE THREAD

**Issue by giard-alexandre** [czeckd/angular-dual-listbox#81]
As it stands, projects that contain this library cannot be upgraded to Angular 6. I would be willing to help, if need be.

**Comment by czeckd** [comment]
I'm investigating. My Angular 6 projects that use it didn't complain, so I wasn't alerted to a problem. Could  you post what you're seeing please?

**Comment by giard-alexandre** [comment]
Actually you're right, I'm sorry it was my mistake. I am no longer getting an error from this lib. Thanks a lot!
