### ISSUE TITLE
Not Display data

### ISSUE THREAD

**Issue by vietdq1291** [czeckd/angular-dual-listbox#89]
I have list object like this 
userlstadd: Array<DualistDepartmentUserObject> = [];
confirmed: Array<DualistDepartmentUserObject> = [];

export class DualistDepartmentUserObject {
  ma: number;
  hoTen: string;
  tenDangNhap: string;
  tongso: number;
}

// Function get data 
  GetUserToAdd(id: number) {
    this.service.DepartmentGetUserToAdd(id).subscribe(data => {
      this.userlstadd = data.gridDepartmentUser;
      $("#modal-adduser").modal('show');
    }, error => {
      alert(error)
    })
  }

//View 
   <dual-list [source]="userlstadd" [key]="ma" [(display)]="hoTen" [(destination)]="confirmed" [format]="format"></dual-list>

  format = {
    add: 'Chọn', remove: 'Bỏ chọn', all: 'Tích tất cả', none: 'Bỏ tích tất cả',
  };

The Dual List not show my data 

![image](https://user-images.githubusercontent.com/38650722/42995338-ccd4987e-8c3a-11e8-8041-f8a03ac5cc7f.png)

**Comment by czeckd** [comment]
Can you show an example of the array being returned by DepartmentGetUserToAdd? Also, you may want to try this in the view instead:
```html
<dual-list [source]="userlstadd" key="ma" display="hoTen" [(destination)]="confirmed"
 [format]="format">
```

Change is: **key="ma" display="hoTen"**.
