### ISSUE TITLE
Extending with a Custom-dual-listbox fails to stat ENOENT in Angular 6+

### ISSUE THREAD

**Issue by nphias** [czeckd/angular-dual-listbox#97]
Hi there i was able to get this module installed and working fine in angular 6 (electron client)
then i decided I wanted to customise styles .. so I extended the module as described in the custom-dual-listbox repo. 

It fails to compile saying that file is not available .. seems to resolve file path to the location of the package module (modules) ./src/* and not the location of where my extending class is located... I imagine this is a bug and html selector <my-dual-list> should find my-dual-list module and component as imported in the feature module

**Comment by czeckd** [comment]
Are you trying to customize this in an Angular CLI project, or the demo app that is part of this repo, or something else? If it is the demo app, then I'm not surprised. I recommend not using that.

I made a quick demo in StackBlitz here: [angular-s24kd2.stackblitz.io](https://stackblitz.com/edit/angular-s24kd2).

**Comment by nphias** [comment]
I am sorry this was a dumb mistake.. i didnt have a relative URL in my templateUrl string.
nice module by the way.. will you be upgrading the packages to angular 7?

**Comment by czeckd** [comment]
Since it is still working with Angular 7, is there a compelling reason to?
