### ISSUE TITLE
Dual-list not rendering correctly with filter=true; filter input boxes appear in the middle of the select lists and filter icons are shifted to the right by approx. the width of the entire dual listbox

### ISSUE THREAD

**Issue by osmolyar** [czeckd/angular-dual-listbox#98]
In Firefox/Chrome/Edge, with filter="true" the css appears as shown below
![image](https://user-images.githubusercontent.com/15637471/53743563-1bc69c80-3e69-11e9-82d5-61dc4e714a26.png)

with the filter input box appearing midway between, and overlapping. the first and second items.   The filter icons are also shifted all the way to the right of the viewport.

**Comment by czeckd** [comment]
In your example, it looks like you are not loading the Bootstrap 3 css. In the demo's index.html:
```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
  integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
```
Here's the [demo](https://czeckd.github.io/angular-dual-listbox/demo/) with Firefox:

![bs3](https://user-images.githubusercontent.com/17859320/54182702-7a8aa800-445f-11e9-8b84-35d2f453c43f.png)
