### ISSUE TITLE
Cant bind an array of json objects to angular-duallistbox with angular 6

### ISSUE THREAD

**Issue by yatharthmishra95** [czeckd/angular-dual-listbox#99]
0

Currently nothing this being displayed in source list, the array of json is

[{deviceId: 101 , deviceName:"UK101"},
{deviceId: 102 , deviceName:"UK102"},
{deviceId: 103 , deviceName:"UK103"}]
I am currently making a service call to fetch this data, My HTML code is

 <dual-list [key]="deviceId" [(display)]="deviceName" [source]="source" 
[(destination)]="target" height="150px"  ></dual-list> 
But still no data is displayed in the lists

**Comment by czeckd** [comment]
Try:
```html
<dual-list key="deviceId" display="deviceName" [source]="source"
[(destination)]="target" height="150px" >
```
Neither your key nor your display are typescript variables in your code, so just bind to the string.

**Comment by yatharthmishra95** [comment]
Thanks very much it works now.

**Comment by vijayakumarrajug** [comment]
Hi Team,
Preselected values are not displaying in right  side box.
The preselected values are array of objects.
example: let selectedList:Array<any> = [
      { key: 26, station: 'Hermosa', state: 'CO' },
    { key: 27, station: 'Rockwood', state: 'CO' },
    { key: 28, station: 'Tacoma', state: 'CO' }
    ];
The  selectedList will be API response.
this.confirmedStations = selectedList;

I'm not able to display on confirmed values on destination box.
<dual-list [sort]="keepSorted" [source]="source" [key]="key" [display]="display" [filter]="filter"
		[(destination)]="confirmed" height="265px" [format]="format" [disabled]="disabled"></dual-list>

Anybody please help me.
@yatharthmishra95
